# Generated by Django 3.0.2 on 2020-01-09 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Primitive', 'Primitive'), ('CORPSE', 'CORPSE'), ('Gaussian', 'Gaussian'), ('CinBB', 'CinBB'), ('CinSK', 'CinSK')], max_length=10)),
                ('maximum_rabi_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.DecimalValidator(7, 5)])),
                ('polar_angle', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1), django.core.validators.DecimalValidator(6, 5)])),
            ],
        ),
    ]
