# Generated by Django 3.0.2 on 2020-01-09 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_auto_20200109_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='maximum_rabi_rate',
            field=models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
